UPDATE category SET deleted = true;
UPDATE question SET deleted = true;
UPDATE single_option SET deleted = true;
INSERT INTO category (id, category_order, name, questionnaire_id) VALUES (nextval('hibernate_sequence'), 0, $$Bridgekeeper Questions$$, 1);
INSERT INTO question (id, question_order, type, name, question_text, description, category_id) VALUES (nextval('hibernate_sequence'), 0, 'SINGLE', $$NAMES$$, $$What... is your name?$$, $$What is the name of the knight being quizzed?$$, (SELECT max(id) FROM category));
INSERT INTO single_option (id, singleoption_order, option, risk, question_id) VALUES (nextval('hibernate_sequence'), 0, $$Sir Lancelot of Camelot$$, 'GREEN', (SELECT max(id) FROM question));
INSERT INTO single_option (id, singleoption_order, option, risk, question_id) VALUES (nextval('hibernate_sequence'), 1, $$Sir Robin of Camelot$$, 'YELLOW', (SELECT max(id) FROM question));
INSERT INTO single_option (id, singleoption_order, option, risk, question_id) VALUES (nextval('hibernate_sequence'), 2, $$Sir Gallahad of Camelot$$, 'RED', (SELECT max(id) FROM question));
INSERT INTO single_option (id, singleoption_order, option, risk, question_id) VALUES (nextval('hibernate_sequence'), 3, $$Arthur, King of the Britons$$, 'UNKNOWN', (SELECT max(id) FROM question));
INSERT INTO question (id, question_order, type, name, question_text, description, category_id) VALUES (nextval('hibernate_sequence'), 1, 'SINGLE', $$QUESTS$$, $$What... is your quest?$$, $$What is the quest that the knight is on?$$, (SELECT max(id) FROM category));
INSERT INTO single_option (id, singleoption_order, option, risk, question_id) VALUES (nextval('hibernate_sequence'), 0, $$I seek the grail.$$, 'GREEN', (SELECT max(id) FROM question));
INSERT INTO single_option (id, singleoption_order, option, risk, question_id) VALUES (nextval('hibernate_sequence'), 1, $$To cross this bridge.$$, 'RED', (SELECT max(id) FROM question));
INSERT INTO question (id, question_order, type, name, question_text, description, category_id) VALUES (nextval('hibernate_sequence'), 2, 'SINGLE', $$SWALLOWS$$, $$What... is the air-speed velocity of an unladen swallow?$$, $$Well?$$, (SELECT max(id) FROM category));
INSERT INTO single_option (id, singleoption_order, option, risk, question_id) VALUES (nextval('hibernate_sequence'), 0, $$African or European?$$, 'GREEN', (SELECT max(id) FROM question));
INSERT INTO single_option (id, singleoption_order, option, risk, question_id) VALUES (nextval('hibernate_sequence'), 1, $$Huh? I… I don’t know that.$$, 'RED', (SELECT max(id) FROM question));
INSERT INTO category (id, category_order, name, questionnaire_id) VALUES (nextval('hibernate_sequence'), 1, $$More Bridgekeeper Questions$$, 1);
INSERT INTO question (id, question_order, type, name, question_text, description, category_id) VALUES (nextval('hibernate_sequence'), 0, 'SINGLE', $$COLORS$$, $$What... is your favorite color?$$, $$What is the knight's favorite color?$$, (SELECT max(id) FROM category));
INSERT INTO single_option (id, singleoption_order, option, risk, question_id) VALUES (nextval('hibernate_sequence'), 0, $$Green$$, 'GREEN', (SELECT max(id) FROM question));
INSERT INTO single_option (id, singleoption_order, option, risk, question_id) VALUES (nextval('hibernate_sequence'), 1, $$Yellow$$, 'YELLOW', (SELECT max(id) FROM question));
INSERT INTO single_option (id, singleoption_order, option, risk, question_id) VALUES (nextval('hibernate_sequence'), 2, $$Blue. No, yellow!$$, 'RED', (SELECT max(id) FROM question));
INSERT INTO single_option (id, singleoption_order, option, risk, question_id) VALUES (nextval('hibernate_sequence'), 3, $$Blue$$, 'UNKNOWN', (SELECT max(id) FROM question));
